(when (equal system-type 'darwin)
  (setq mac-command-modifier 'meta)
  (setq mac-option-modifier 'super)
  ;; (add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
  ;; (add-to-list 'default-frame-alist '(ns-appearance . dark))
  ;; (when (member "Fira Code" (font-family-list))
  ;;   (add-to-list 'initial-frame-alist '(font . "Fira Code-14"))
  ;;   (add-to-list 'default-frame-alist '(font . "Fira Code-14")))
  ;; (set-fontset-font t 'symbol (font-spec :family "Apple Symbols") nil 'prepend)
  ;; (set-fontset-font t 'symbol (font-spec :family "Apple Color Emoji") nil 'prepend)
  )

(provide 'dave-mac)
